import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/auth-proivder";

export const metadata: Metadata = {
  title: "Dashboard with Auth",
  description: "Generated by amir hossien heydarpoor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
